//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Btssio.Escrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARME
    {
        public ARME()
        {
            this.MAITREDARME = new HashSet<MAITREDARME>();
        }
    
        public int CODEARME { get; set; }
        public string NOMARME { get; set; }
    
        public virtual ICollection<MAITREDARME> MAITREDARME { get; set; }
    }
}
