//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Btssio.Escrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIE
    {
        public CATEGORIE()
        {
            this.COMPETITION = new HashSet<COMPETITION>();
            this.ESCRIMEUR = new HashSet<ESCRIMEUR>();
        }
    
        public int CODECATEG { get; set; }
        public string NOMCATEG { get; set; }
    
        public virtual ICollection<COMPETITION> COMPETITION { get; set; }
        public virtual ICollection<ESCRIMEUR> ESCRIMEUR { get; set; }
    }
}
