//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCRIMEUR
    {
        public string NUMLICENCEESCRIMEUR { get; set; }
        public int CODECATEG { get; set; }
        public int NUMCLUB { get; set; }
        public string NOMESCRIMEUR { get; set; }
        public string PRENOMESCRIMEUR { get; set; }
        public Nullable<System.DateTime> DATENAISSESCRIMEUR { get; set; }
    
        public virtual CATEGORIE CATEGORIE { get; set; }
        public virtual CLUB CLUB { get; set; }
    }
}
